apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  namespace: argocd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      # imagePullSecrets:
      #   - name: regcred
      containers:
        - name: my-app-container
          image: 684206014294.dkr.ecr.us-east-1.amazonaws.com/argocd:ubuntu-latest
          ports:
            - containerPort: 80